### ISSUE TITLE
Fix output when redirected

### ISSUE THREAD

**Issue by isuruf** [isuruf/flang#33]
When running `ab20.exe` it prints a message but `ab20.exe > file.txt` would create an empty file.

This needs to be fixed to run the tests.

**Comment by ghost** [comment]
Is this from MSYS2?

**Comment by isuruf** [comment]
In both `cmd` and `bash`. (It's not hello_world program though, https://github.com/flang-compiler/flang/blob/master/test/f90_correct/src/ab00.f)

**Comment by isuruf** [comment]
This seems to work now
