### ISSUE TITLE
Rethink using Dbghelp and Ws2_32

### ISSUE THREAD

**Issue by isuruf** [isuruf/flang#37]
These dlls are not shipped by default and it's better if we can only depend on visual c redistributable dlls.

**Comment by ghost** [comment]
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/132fab64-e1a3-456d-959a-b2e177a271f7/can-i-statically-link-dbghelplib-and-distribute-my-c-application?forum=windbg

**Comment by ghost** [comment]
In other words, include statically in runtime dll.

**Comment by ghost** [comment]
Actually this is impossible, as they don't include the static libs.

**Comment by ghost** [comment]
resolved by #43 and #42.
