### ISSUE TITLE
Cannot bootstrap from source using appveyor

### ISSUE THREAD

**Issue by ghost** [isuruf/flang#94]

**Comment by isuruf** [comment]
Can you provide details?

**Comment by ghost** [comment]
This is related to the CMake failures. `flang` builds fine:

- On my local computer when the `flang` package is not installed
- On Appveyor when the CMake generator is not "Ninja"
- On Appveyor when the `flang` package is installed

Cmake configuration fails when:

- On appveyor, with the "Ninja" generator, and when `flang` is not installed

**Comment by ghost** [comment]
Simply remove `flang` from this line and it should fail:

https://github.com/isuruf/flang/blob/248665791ce5f1de559d1eb774c7dedc8eb68fb9/.appveyor.yml#L23

**Comment by isuruf** [comment]
Fixed in https://github.com/isuruf/flang/pull/95
